# These are supported funding model platforms

github: [amarkes]
issuehunt: https://github.com/amarkes/finanflow/issues
thanks_dev: https://thanks.dev/profiles
custom: ['https://github.com/sponsors/amarkes']
